### ISSUE TITLE
Error when parse some xml file

### ISSUE THREAD

**Issue by changecong** [changecong/dl-example#22]
File name: CHT_CMN_20130329.0000.su.xml

While read data from this file, following Error occurs

Traceback (most recent call last):
  File "test_all.py", line 22, in <module>
    xml_metadata = xmlreader.label_sentences(xmlreader.get_text(), tags)
  File "/home/c/gema/workspaces/dl-example/src/metadata/generator.py", line 109, in label_sentences
    if tags.get(str(start_position + index + 1), False):
TypeError: coercing to Unicode: need string or buffer, int found

**Comment by changecong** [comment]
Fixed

https://github.com/changecong/dl-example/pull/23
